version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: digital-greenhouse-postgres
    environment:
      POSTGRES_DB: digital_greenhouse
      POSTGRES_USER: garden_user
      POSTGRES_PASSWORD: garden_secret_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U garden_user -d digital_greenhouse"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: digital-greenhouse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: digital-greenhouse-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://garden_user:garden_secret_2024@postgres:5432/digital_greenhouse
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Database Migration Service
  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: migrate
    container_name: digital-greenhouse-migration
    environment:
      - DATABASE_URL=postgresql://garden_user:garden_secret_2024@postgres:5432/digital_greenhouse
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  # Celery Worker (Background Tasks)
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: celery-worker
    container_name: digital-greenhouse-celery
    environment:
      - DATABASE_URL=postgresql://garden_user:garden_secret_2024@postgres:5432/digital_greenhouse
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Celery Beat (Scheduled Tasks)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: celery-beat
    container_name: digital-greenhouse-beat
    environment:
      - DATABASE_URL=postgresql://garden_user:garden_secret_2024@postgres:5432/digital_greenhouse
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: