# Prometheus configuration for Digital Greenhouse monitoring
# Comprehensive metrics collection for performance, health, and business analytics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'digital-greenhouse'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load and evaluate rules in these files every 'evaluation_interval' seconds
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Digital Greenhouse Backend API
  - job_name: 'digital-greenhouse-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Digital Greenhouse Frontend (Nginx metrics)
  - job_name: 'digital-greenhouse-frontend'
    static_configs:
      - targets: ['frontend:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Blackbox exporter for uptime monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://digital-greenhouse.dev
        - https://api.digital-greenhouse.dev
        - https://staging.digital-greenhouse.dev
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom business metrics
  - job_name: 'digital-greenhouse-business'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics/business'
    scrape_interval: 60s
    scrape_timeout: 15s

  # External API monitoring
  - job_name: 'external-apis'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics/external'
    scrape_interval: 120s
    scrape_timeout: 30s

  # Performance and user experience metrics
  - job_name: 'digital-greenhouse-ux'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics/ux'
    scrape_interval: 30s
    scrape_timeout: 10s

# Remote write configuration (for external storage)
# remote_write:
#   - url: "https://monitoring-service.example.com/api/v1/write"
#     basic_auth:
#       username: "prometheus"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Web interface configuration
web:
  console.libraries: /etc/prometheus/console_libraries
  console.templates: /etc/prometheus/consoles
  enable-lifecycle: true
  enable-admin-api: true